"""Initial migration

Revision ID: 3bd154ad0510
Revises: 
Create Date: 2025-11-04 21:20:59.217457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd154ad0510'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('work_experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('projects', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('achievements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('accepts_contact_requests', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni', schema=None) as batch_op:
        batch_op.drop_column('accepts_contact_requests')
        batch_op.drop_column('achievements')
        batch_op.drop_column('projects')
        batch_op.drop_column('education')
        batch_op.drop_column('work_experience')
        batch_op.drop_column('about')

    # ### end Alembic commands ###
